USE ai_lawyer_db;

-- Добавляем 15 недостающих шаблонов с правильными категориями

-- ФИНАНСОВЫЕ ДОГОВОРЫ (3 шт)
INSERT INTO contract_templates (name, category, description, template_content, variables) VALUES 
('Договор банковского вклада', 'financial', 'Договор банковского вклада физического лица', 
'<div style="text-align: center; font-weight: bold; font-size: 16pt; margin-bottom: 30px;">ДОГОВОР БАНКОВСКОГО ВКЛАДА № {{contract_number}}</div><div style="text-align: right; margin-bottom: 20px;">г. {{city}}, {{contract_date}}</div><p style="text-align: justify;">{{bank_name}}, именуемый "Банк", и {{depositor_name}}, именуемый "Вкладчик", заключили договор о банковском вкладе.</p><p>1.1. Размер вклада: {{deposit_amount}} рублей под {{interest_rate}}% годовых.</p><table width="100%" style="margin-top: 30px;"><tr><td width="50%" style="text-align: center;"><strong>Банк:</strong><br/>{{bank_name}}<br/><div style="border-bottom: 1px solid black; width: 150px; margin: 20px auto;"></div>/{{bank_signature}}/</td><td width="50%" style="text-align: center;"><strong>Вкладчик:</strong><br/>{{depositor_name}}<br/><div style="border-bottom: 1px solid black; width: 150px; margin: 20px auto;"></div>/{{depositor_signature}}/</td></tr></table>', 
JSON_OBJECT('contract_number', 'Номер договора', 'city', 'Город', 'contract_date', 'Дата', 'bank_name', 'Банк', 'depositor_name', 'Вкладчик', 'deposit_amount', 'Сумма', 'interest_rate', 'Процент', 'bank_signature', 'Подпись банка', 'depositor_signature', 'Подпись вкладчика')),

('Договор лизинга', 'financial', 'Договор финансовой аренды', 
'<div style="text-align: center; font-weight: bold; font-size: 16pt; margin-bottom: 30px;">ДОГОВОР ЛИЗИНГА № {{contract_number}}</div><div style="text-align: right; margin-bottom: 20px;">г. {{city}}, {{contract_date}}</div><p style="text-align: justify;">{{lessor_name}}, именуемый "Лизингодатель", и {{lessee_name}}, именуемый "Лизингополучатель", заключили договор лизинга.</p><p>1.1. Предмет лизинга: {{leased_property}}.</p><p>2.1. Лизинговый платеж: {{lease_payment}} рублей в месяц.</p><table width="100%" style="margin-top: 30px;"><tr><td width="50%" style="text-align: center;"><strong>Лизингодатель:</strong><br/>{{lessor_name}}<br/><div style="border-bottom: 1px solid black; width: 150px; margin: 20px auto;"></div>/{{lessor_signature}}/</td><td width="50%" style="text-align: center;"><strong>Лизингополучатель:</strong><br/>{{lessee_name}}<br/><div style="border-bottom: 1px solid black; width: 150px; margin: 20px auto;"></div>/{{lessee_signature}}/</td></tr></table>', 
JSON_OBJECT('contract_number', 'Номер договора', 'city', 'Город', 'contract_date', 'Дата', 'lessor_name', 'Лизингодатель', 'lessee_name', 'Лизингополучатель', 'leased_property', 'Предмет лизинга', 'lease_payment', 'Платеж', 'lessor_signature', 'Подпись лизингодателя', 'lessee_signature', 'Подпись лизингополучателя')),

('Договор факторинга', 'financial', 'Договор финансирования под уступку требования', 
'<div style="text-align: center; font-weight: bold; font-size: 16pt; margin-bottom: 30px;">ДОГОВОР ФАКТОРИНГА № {{contract_number}}</div><div style="text-align: right; margin-bottom: 20px;">г. {{city}}, {{contract_date}}</div><p style="text-align: justify;">{{factor_name}}, именуемый "Фактор", и {{client_name}}, именуемый "Клиент", заключили договор факторинга.</p><p>1.1. Сумма требования: {{claim_amount}} рублей.</p><table width="100%" style="margin-top: 30px;"><tr><td width="50%" style="text-align: center;"><strong>Фактор:</strong><br/>{{factor_name}}<br/><div style="border-bottom: 1px solid black; width: 150px; margin: 20px auto;"></div>/{{factor_signature}}/</td><td width="50%" style="text-align: center;"><strong>Клиент:</strong><br/>{{client_name}}<br/><div style="border-bottom: 1px solid black; width: 150px; margin: 20px auto;"></div>/{{client_signature}}/</td></tr></table>', 
JSON_OBJECT('contract_number', 'Номер договора', 'city', 'Город', 'contract_date', 'Дата', 'factor_name', 'Фактор', 'client_name', 'Клиент', 'claim_amount', 'Сумма требования', 'factor_signature', 'Подпись фактора', 'client_signature', 'Подпись клиента')),

-- КОММЕРЧЕСКИЕ ДОГОВОРЫ (3 шт)
('Договор поручения', 'commercial', 'Договор поручения на совершение действий', 
'<div style="text-align: center; font-weight: bold; font-size: 16pt; margin-bottom: 30px;">ДОГОВОР ПОРУЧЕНИЯ № {{contract_number}}</div><div style="text-align: right; margin-bottom: 20px;">г. {{city}}, {{contract_date}}</div><p style="text-align: justify;">{{principal_name}}, именуемый "Доверитель", и {{agent_name}}, именуемый "Поверенный", заключили договор поручения.</p><p>1.1. Предмет поручения: {{task_description}}.</p><table width="100%" style="margin-top: 30px;"><tr><td width="50%" style="text-align: center;"><strong>Доверитель:</strong><br/>{{principal_name}}<br/><div style="border-bottom: 1px solid black; width: 150px; margin: 20px auto;"></div>/{{principal_signature}}/</td><td width="50%" style="text-align: center;"><strong>Поверенный:</strong><br/>{{agent_name}}<br/><div style="border-bottom: 1px solid black; width: 150px; margin: 20px auto;"></div>/{{agent_signature}}/</td></tr></table>', 
JSON_OBJECT('contract_number', 'Номер договора', 'city', 'Город', 'contract_date', 'Дата', 'principal_name', 'Доверитель', 'agent_name', 'Поверенный', 'task_description', 'Описание поручения', 'principal_signature', 'Подпись доверителя', 'agent_signature', 'Подпись поверенного')),

('Договор простого товарищества', 'commercial', 'Договор о совместной деятельности', 
'<div style="text-align: center; font-weight: bold; font-size: 16pt; margin-bottom: 30px;">ДОГОВОР ПРОСТОГО ТОВАРИЩЕСТВА № {{contract_number}}</div><div style="text-align: right; margin-bottom: 20px;">г. {{city}}, {{contract_date}}</div><p style="text-align: justify;">{{partner1_name}} и {{partner2_name}} заключили договор простого товарищества.</p><p>1.1. Цель деятельности: {{business_purpose}}.</p><table width="100%" style="margin-top: 30px;"><tr><td width="50%" style="text-align: center;"><strong>Товарищ 1:</strong><br/>{{partner1_name}}<br/><div style="border-bottom: 1px solid black; width: 150px; margin: 20px auto;"></div>/{{partner1_signature}}/</td><td width="50%" style="text-align: center;"><strong>Товарищ 2:</strong><br/>{{partner2_name}}<br/><div style="border-bottom: 1px solid black; width: 150px; margin: 20px auto;"></div>/{{partner2_signature}}/</td></tr></table>', 
JSON_OBJECT('contract_number', 'Номер договора', 'city', 'Город', 'contract_date', 'Дата', 'partner1_name', 'Товарищ 1', 'partner2_name', 'Товарищ 2', 'business_purpose', 'Цель деятельности', 'partner1_signature', 'Подпись товарища 1', 'partner2_signature', 'Подпись товарища 2')),

('Договор коммерческой концессии', 'commercial', 'Договор франчайзинга', 
'<div style="text-align: center; font-weight: bold; font-size: 16pt; margin-bottom: 30px;">ДОГОВОР КОММЕРЧЕСКОЙ КОНЦЕССИИ № {{contract_number}}</div><div style="text-align: right; margin-bottom: 20px;">г. {{city}}, {{contract_date}}</div><p style="text-align: justify;">{{franchisor_name}}, именуемый "Правообладатель", и {{franchisee_name}}, именуемый "Пользователь", заключили договор коммерческой концессии.</p><p>1.1. Предмет концессии: {{franchise_subject}}.</p><table width="100%" style="margin-top: 30px;"><tr><td width="50%" style="text-align: center;"><strong>Правообладатель:</strong><br/>{{franchisor_name}}<br/><div style="border-bottom: 1px solid black; width: 150px; margin: 20px auto;"></div>/{{franchisor_signature}}/</td><td width="50%" style="text-align: center;"><strong>Пользователь:</strong><br/>{{franchisee_name}}<br/><div style="border-bottom: 1px solid black; width: 150px; margin: 20px auto;"></div>/{{franchisee_signature}}/</td></tr></table>', 
JSON_OBJECT('contract_number', 'Номер договора', 'city', 'Город', 'contract_date', 'Дата', 'franchisor_name', 'Правообладатель', 'franchisee_name', 'Пользователь', 'franchise_subject', 'Предмет концессии', 'franchisor_signature', 'Подпись правообладателя', 'franchisee_signature', 'Подпись пользователя')),

-- НЕДВИЖИМОСТЬ (2 шт)
('Договор мены недвижимости', 'real_estate', 'Договор мены недвижимого имущества', 
'<div style="text-align: center; font-weight: bold; font-size: 16pt; margin-bottom: 30px;">ДОГОВОР МЕНЫ НЕДВИЖИМОСТИ № {{contract_number}}</div><div style="text-align: right; margin-bottom: 20px;">г. {{city}}, {{contract_date}}</div><p style="text-align: justify;">{{party1_name}} и {{party2_name}} заключили договор мены недвижимости.</p><p>1.1. Объект 1: {{property1_description}}.</p><p>1.2. Объект 2: {{property2_description}}.</p><table width="100%" style="margin-top: 30px;"><tr><td width="50%" style="text-align: center;"><strong>Сторона 1:</strong><br/>{{party1_name}}<br/><div style="border-bottom: 1px solid black; width: 150px; margin: 20px auto;"></div>/{{party1_signature}}/</td><td width="50%" style="text-align: center;"><strong>Сторона 2:</strong><br/>{{party2_name}}<br/><div style="border-bottom: 1px solid black; width: 150px; margin: 20px auto;"></div>/{{party2_signature}}/</td></tr></table>', 
JSON_OBJECT('contract_number', 'Номер договора', 'city', 'Город', 'contract_date', 'Дата', 'party1_name', 'Сторона 1', 'party2_name', 'Сторона 2', 'property1_description', 'Объект 1', 'property2_description', 'Объект 2', 'party1_signature', 'Подпись стороны 1', 'party2_signature', 'Подпись стороны 2')),

('Договор долевого участия в строительстве', 'real_estate', 'Договор участия в долевом строительстве', 
'<div style="text-align: center; font-weight: bold; font-size: 16pt; margin-bottom: 30px;">ДОГОВОР ДОЛЕВОГО УЧАСТИЯ В СТРОИТЕЛЬСТВЕ № {{contract_number}}</div><div style="text-align: right; margin-bottom: 20px;">г. {{city}}, {{contract_date}}</div><p style="text-align: justify;">{{developer_name}}, именуемый "Застройщик", и {{participant_name}}, именуемый "Участник", заключили договор долевого участия.</p><p>1.1. Объект строительства: {{construction_object}}.</p><table width="100%" style="margin-top: 30px;"><tr><td width="50%" style="text-align: center;"><strong>Застройщик:</strong><br/>{{developer_name}}<br/><div style="border-bottom: 1px solid black; width: 150px; margin: 20px auto;"></div>/{{developer_signature}}/</td><td width="50%" style="text-align: center;"><strong>Участник:</strong><br/>{{participant_name}}<br/><div style="border-bottom: 1px solid black; width: 150px; margin: 20px auto;"></div>/{{participant_signature}}/</td></tr></table>', 
JSON_OBJECT('contract_number', 'Номер договора', 'city', 'Город', 'contract_date', 'Дата', 'developer_name', 'Застройщик', 'participant_name', 'Участник', 'construction_object', 'Объект строительства', 'developer_signature', 'Подпись застройщика', 'participant_signature', 'Подпись участника')),

-- СЕМЕЙНЫЕ ДОГОВОРЫ (2 шт)
('Соглашение об уплате алиментов', 'family', 'Соглашение об уплате алиментов на ребенка', 
'<div style="text-align: center; font-weight: bold; font-size: 16pt; margin-bottom: 30px;">СОГЛАШЕНИЕ ОБ УПЛАТЕ АЛИМЕНТОВ № {{contract_number}}</div><div style="text-align: right; margin-bottom: 20px;">г. {{city}}, {{contract_date}}</div><p style="text-align: justify;">{{payer_name}}, именуемый "Плательщик", и {{recipient_name}}, именуемый "Получатель", заключили соглашение об алиментах.</p><p>1.1. Размер алиментов: {{alimony_amount}} рублей в месяц.</p><table width="100%" style="margin-top: 30px;"><tr><td width="50%" style="text-align: center;"><strong>Плательщик:</strong><br/>{{payer_name}}<br/><div style="border-bottom: 1px solid black; width: 150px; margin: 20px auto;"></div>/{{payer_signature}}/</td><td width="50%" style="text-align: center;"><strong>Получатель:</strong><br/>{{recipient_name}}<br/><div style="border-bottom: 1px solid black; width: 150px; margin: 20px auto;"></div>/{{recipient_signature}}/</td></tr></table>', 
JSON_OBJECT('contract_number', 'Номер договора', 'city', 'Город', 'contract_date', 'Дата', 'payer_name', 'Плательщик', 'recipient_name', 'Получатель', 'alimony_amount', 'Размер алиментов', 'payer_signature', 'Подпись плательщика', 'recipient_signature', 'Подпись получателя')),

('Соглашение о порядке общения с ребенком', 'family', 'Соглашение родителей о порядке общения', 
'<div style="text-align: center; font-weight: bold; font-size: 16pt; margin-bottom: 30px;">СОГЛАШЕНИЕ О ПОРЯДКЕ ОБЩЕНИЯ С РЕБЕНКОМ № {{contract_number}}</div><div style="text-align: right; margin-bottom: 20px;">г. {{city}}, {{contract_date}}</div><p style="text-align: justify;">{{parent1_name}} и {{parent2_name}} заключили соглашение о порядке общения с ребенком {{child_name}}.</p><p>1.1. График общения: {{communication_schedule}}.</p><table width="100%" style="margin-top: 30px;"><tr><td width="50%" style="text-align: center;"><strong>Родитель 1:</strong><br/>{{parent1_name}}<br/><div style="border-bottom: 1px solid black; width: 150px; margin: 20px auto;"></div>/{{parent1_signature}}/</td><td width="50%" style="text-align: center;"><strong>Родитель 2:</strong><br/>{{parent2_name}}<br/><div style="border-bottom: 1px solid black; width: 150px; margin: 20px auto;"></div>/{{parent2_signature}}/</td></tr></table>', 
JSON_OBJECT('contract_number', 'Номер договора', 'city', 'Город', 'contract_date', 'Дата', 'parent1_name', 'Родитель 1', 'parent2_name', 'Родитель 2', 'child_name', 'Ребенок', 'communication_schedule', 'График общения', 'parent1_signature', 'Подпись родителя 1', 'parent2_signature', 'Подпись родителя 2')),

-- ТРАНСПОРТ (1 шт)
('Договор аренды транспортного средства', 'transport', 'Договор аренды автомобиля', 
'<div style="text-align: center; font-weight: bold; font-size: 16pt; margin-bottom: 30px;">ДОГОВОР АРЕНДЫ ТРАНСПОРТНОГО СРЕДСТВА № {{contract_number}}</div><div style="text-align: right; margin-bottom: 20px;">г. {{city}}, {{contract_date}}</div><p style="text-align: justify;">{{lessor_name}}, именуемый "Арендодатель", и {{lessee_name}}, именуемый "Арендатор", заключили договор аренды транспорта.</p><p>1.1. Транспортное средство: {{vehicle_description}}.</p><table width="100%" style="margin-top: 30px;"><tr><td width="50%" style="text-align: center;"><strong>Арендодатель:</strong><br/>{{lessor_name}}<br/><div style="border-bottom: 1px solid black; width: 150px; margin: 20px auto;"></div>/{{lessor_signature}}/</td><td width="50%" style="text-align: center;"><strong>Арендатор:</strong><br/>{{lessee_name}}<br/><div style="border-bottom: 1px solid black; width: 150px; margin: 20px auto;"></div>/{{lessee_signature}}/</td></tr></table>', 
JSON_OBJECT('contract_number', 'Номер договора', 'city', 'Город', 'contract_date', 'Дата', 'lessor_name', 'Арендодатель', 'lessee_name', 'Арендатор', 'vehicle_description', 'Описание ТС', 'lessor_signature', 'Подпись арендодателя', 'lessee_signature', 'Подпись арендатора')),

-- СТРОИТЕЛЬСТВО (1 шт)
('Договор на выполнение проектных работ', 'construction', 'Договор на разработку проекта', 
'<div style="text-align: center; font-weight: bold; font-size: 16pt; margin-bottom: 30px;">ДОГОВОР НА ВЫПОЛНЕНИЕ ПРОЕКТНЫХ РАБОТ № {{contract_number}}</div><div style="text-align: right; margin-bottom: 20px;">г. {{city}}, {{contract_date}}</div><p style="text-align: justify;">{{customer_name}}, именуемый "Заказчик", и {{contractor_name}}, именуемый "Подрядчик", заключили договор на проектные работы.</p><p>1.1. Объект проектирования: {{project_object}}.</p><table width="100%" style="margin-top: 30px;"><tr><td width="50%" style="text-align: center;"><strong>Заказчик:</strong><br/>{{customer_name}}<br/><div style="border-bottom: 1px solid black; width: 150px; margin: 20px auto;"></div>/{{customer_signature}}/</td><td width="50%" style="text-align: center;"><strong>Подрядчик:</strong><br/>{{contractor_name}}<br/><div style="border-bottom: 1px solid black; width: 150px; margin: 20px auto;"></div>/{{contractor_signature}}/</td></tr></table>', 
JSON_OBJECT('contract_number', 'Номер договора', 'city', 'Город', 'contract_date', 'Дата', 'customer_name', 'Заказчик', 'contractor_name', 'Подрядчик', 'project_object', 'Объект проектирования', 'customer_signature', 'Подпись заказчика', 'contractor_signature', 'Подпись подрядчика')),

-- ИНТЕЛЛЕКТУАЛЬНАЯ СОБСТВЕННОСТЬ (1 шт)
('Договор авторского заказа', 'intellectual', 'Договор на создание произведения', 
'<div style="text-align: center; font-weight: bold; font-size: 16pt; margin-bottom: 30px;">ДОГОВОР АВТОРСКОГО ЗАКАЗА № {{contract_number}}</div><div style="text-align: right; margin-bottom: 20px;">г. {{city}}, {{contract_date}}</div><p style="text-align: justify;">{{customer_name}}, именуемый "Заказчик", и {{author_name}}, именуемый "Автор", заключили договор авторского заказа.</p><p>1.1. Произведение: {{work_description}}.</p><table width="100%" style="margin-top: 30px;"><tr><td width="50%" style="text-align: center;"><strong>Заказчик:</strong><br/>{{customer_name}}<br/><div style="border-bottom: 1px solid black; width: 150px; margin: 20px auto;"></div>/{{customer_signature}}/</td><td width="50%" style="text-align: center;"><strong>Автор:</strong><br/>{{author_name}}<br/><div style="border-bottom: 1px solid black; width: 150px; margin: 20px auto;"></div>/{{author_signature}}/</td></tr></table>', 
JSON_OBJECT('contract_number', 'Номер договора', 'city', 'Город', 'contract_date', 'Дата', 'customer_name', 'Заказчик', 'author_name', 'Автор', 'work_description', 'Описание произведения', 'customer_signature', 'Подпись заказчика', 'author_signature', 'Подпись автора')),

-- ДОВЕРИТЕЛЬНОЕ УПРАВЛЕНИЕ (1 шт)
('Договор управления ценными бумагами', 'trust', 'Договор доверительного управления', 
'<div style="text-align: center; font-weight: bold; font-size: 16pt; margin-bottom: 30px;">ДОГОВОР УПРАВЛЕНИЯ ЦЕННЫМИ БУМАГАМИ № {{contract_number}}</div><div style="text-align: right; margin-bottom: 20px;">г. {{city}}, {{contract_date}}</div><p style="text-align: justify;">{{trustor_name}}, именуемый "Учредитель", и {{trustee_name}}, именуемый "Управляющий", заключили договор управления.</p><p>1.1. Ценные бумаги: {{securities_description}}.</p><table width="100%" style="margin-top: 30px;"><tr><td width="50%" style="text-align: center;"><strong>Учредитель:</strong><br/>{{trustor_name}}<br/><div style="border-bottom: 1px solid black; width: 150px; margin: 20px auto;"></div>/{{trustor_signature}}/</td><td width="50%" style="text-align: center;"><strong>Управляющий:</strong><br/>{{trustee_name}}<br/><div style="border-bottom: 1px solid black; width: 150px; margin: 20px auto;"></div>/{{trustee_signature}}/</td></tr></table>', 
JSON_OBJECT('contract_number', 'Номер договора', 'city', 'Город', 'contract_date', 'Дата', 'trustor_name', 'Учредитель', 'trustee_name', 'Управляющий', 'securities_description', 'Описание ценных бумаг', 'trustor_signature', 'Подпись учредителя', 'trustee_signature', 'Подпись управляющего')),

-- ГРАЖДАНСКИЕ ДОГОВОРЫ (1 шт)
('Договор ренты', 'civil', 'Договор пожизненной ренты', 
'<div style="text-align: center; font-weight: bold; font-size: 16pt; margin-bottom: 30px;">ДОГОВОР РЕНТЫ № {{contract_number}}</div><div style="text-align: right; margin-bottom: 20px;">г. {{city}}, {{contract_date}}</div><p style="text-align: justify;">{{rent_payer_name}}, именуемый "Плательщик ренты", и {{rent_recipient_name}}, именуемый "Получатель ренты", заключили договор ренты.</p><p>1.1. Размер ренты: {{rent_amount}} рублей в месяц.</p><table width="100%" style="margin-top: 30px;"><tr><td width="50%" style="text-align: center;"><strong>Плательщик:</strong><br/>{{rent_payer_name}}<br/><div style="border-bottom: 1px solid black; width: 150px; margin: 20px auto;"></div>/{{rent_payer_signature}}/</td><td width="50%" style="text-align: center;"><strong>Получатель:</strong><br/>{{rent_recipient_name}}<br/><div style="border-bottom: 1px solid black; width: 150px; margin: 20px auto;"></div>/{{rent_recipient_signature}}/</td></tr></table>', 
JSON_OBJECT('contract_number', 'Номер договора', 'city', 'Город', 'contract_date', 'Дата', 'rent_payer_name', 'Плательщик ренты', 'rent_recipient_name', 'Получатель ренты', 'rent_amount', 'Размер ренты', 'rent_payer_signature', 'Подпись плательщика', 'rent_recipient_signature', 'Подпись получателя'));

-- Проверяем результат
SELECT category, COUNT(*) as count FROM contract_templates GROUP BY category ORDER BY count DESC; 